//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EodrLngMembrane {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EodrLngMembraneMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EodrLngMembraneMessageResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EodrLngMembrane.EodrLngMembraneMessageResource", typeof(EodrLngMembraneMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Do you want to close? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CloseFormConfirmation {
            get {
                return ResourceManager.GetString("CloseFormConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete selected measurement data. are you sure ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeleteDataConfirmation {
            get {
                return ResourceManager.GetString("DeleteDataConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to quit? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExitConfirmation {
            get {
                return ResourceManager.GetString("ExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoRequiredData {
            get {
                return ResourceManager.GetString("NoRequiredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Must be {0} to {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutOfRangeData {
            get {
                return ResourceManager.GetString("OutOfRangeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output file of  {0}. are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrintConfirmation {
            get {
                return ResourceManager.GetString("PrintConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラムを終了します。(Program is quit.) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QuitProgram {
            get {
                return ResourceManager.GetString("QuitProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save your input data. are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveEntryForm {
            get {
                return ResourceManager.GetString("SaveEntryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tank Calculation Data Report に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TankCalculationReport {
            get {
                return ResourceManager.GetString("TankCalculationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tank Measurement Data Report に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TankMeasurementReport {
            get {
                return ResourceManager.GetString("TankMeasurementReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tank Shape Data Report に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TankShapeReport {
            get {
                return ResourceManager.GetString("TankShapeReport", resourceCulture);
            }
        }
    }
}
